# Generated by Django 3.1.3 on 2021-10-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location_parking',
            new_name='LocationParking',
        ),
        migrations.RenameModel(
            old_name='Location_stat',
            new_name='LocationStat',
        ),
    ]
