# Generated by Django 3.1.3 on 2021-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211003_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(max_length=10),
        ),
    ]
