# Generated by Django 3.1.3 on 2021-10-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211003_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationparking',
            name='location_name',
            field=models.CharField(default='anonymouse', max_length=255),
            preserve_default=False,
        ),
    ]
