# Generated by Django 3.1.3 on 2021-10-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_locationparking_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationstat',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='locationparking',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='locationparking',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='locationparking',
            name='sub_location',
        ),
        migrations.RemoveField(
            model_name='locationstat',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='locationstat',
            name='sub_location',
        ),
        migrations.AddField(
            model_name='locationparking',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationstat',
            name='available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationstat',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
            preserve_default=False,
        ),
    ]
