# Generated by Django 3.1.3 on 2021-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211003_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationstat',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
